### ISSUE TITLE
dependency Repository not found

### ISSUE THREAD

**Issue by xinminsu** [BlossomLabs/web3-turbo-template#5]
github.com/hugomrdias/concat-stream.git   Repository not found

**Comment by xinminsu** [comment]
Scope: all 9 workspace projects
/home/sxm/hackathon/web3-turbo-template/pkg/subgraph:
 ERROR  Command failed with exit code 128: git ls-remote --refs git+ssh://git@github.com/hugomrdias/concat-stream.git feat/smaller
ERROR: Repository not found.
fatal: 无法读取远程仓库。

请确认您有正确的访问权限并且仓库存在。

This error happened while installing the dependencies of @graphprotocol/graph-cli@0.37.2
 at ipfs-http-client@34.0.0

pnpm: Command failed with exit code 128: git ls-remote --refs git+ssh://git@github.com/hugomrdias/concat-stream.git feat/smaller
ERROR: Repository not found.
fatal: 无法读取远程仓库。

请确认您有正确的访问权限并且仓库存在。
    at makeError (/home/sxm/.nvm/versions/node/v20.4.0/lib/node_modules/pnpm/dist/pnpm.cjs:24966:17)
    at handlePromise (/home/sxm/.nvm/versions/node/v20.4.0/lib/node_modules/pnpm/dist/pnpm.cjs:25537:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getRepoRefs (/home/sxm/.nvm/versions/node/v20.4.0/lib/node_modules/pnpm/dist/pnpm.cjs:110687:23)
    at async resolveRef (/home/sxm/.nvm/versions/node/v20.4.0/lib/node_modules/pnpm/dist/pnpm.cjs:110699:20)
    at async resolveGit (/home/sxm/.nvm/versions/node/v20.4.0/lib/node_modules/pnpm/dist/pnpm.cjs:110650:24)
    at async Object.resolve (/home/sxm/.nvm/versions/node/v20.4.0/lib/node_modules/pnpm/dist/pnpm.cjs:110949:173)
    at async run (/home/sxm/.nvm/versions/node/v20.4.0/lib/node_modules/pnpm/dist/pnpm.cjs:123088:23)
Progress: resolved 1099, reused 1061, downloaded 0, added 0
